ALTER TYPE "DiningTableStatus" ADD VALUE IF NOT EXISTS 'OCCUPIED';
ALTER TYPE "DiningTableStatus" ADD VALUE IF NOT EXISTS 'RESERVED';
ALTER TYPE "DiningTableStatus" ADD VALUE IF NOT EXISTS 'OUT_OF_SERVICE';
